# https://github.com/crate-ci/typos/blob/master/docs/reference.md

[files]
extend-exclude = ["bin", "fixtures", "log", "tmp", "vendor", "*.png"]
ignore-hidden = true

[default.extend-identifiers]

[default.extend-words]
referer = 'referer'
readed_at = 'readed_at'
readed = 'readed'
Rememberable = 'Rememberable'
Feild = 'Feild'
Serivce = 'Serivce'
Reseration = 'Reseration'
placholder = 'placholder'
informations = 'informations'
acccount = 'acccount'
payed = 'payed'
mixpanel = 'mixpanel'
xdescribe = 'xdescribe'
skippable = 'skippable'

[type.typos]
extend-glob = [".typos.toml"]
check-file = false
