# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 491afb28daca0cc4dae4334f3f5d906a0d6323f0ab01abede25ca3cb6d9848161c86e11aa6e74ebfe84a635d8207491d644393215635f1218a2c431508b6f03e
  message_encryptor_key: 80c06b0d2d03125008d26496c2a741cc7ae56635834ccc6c1a092cf8c7f675f369395ae7f00518e8ac3746d47afc8af0d7b9dbec119a5274c1ab66a7f99af6a1
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_from_phone: <%= ENV["TWILIO_FROM_PHONE"] %>
  web_push_public_key: <%= ENV["WEB_PUSH_PUBLIC_KEY"] %>
  web_push_private_key: <%= ENV["WEB_PUSH_PRIVATE_KEY"] %>
  toruya_user_bot_token: <%= ENV["TORUYA_USER_BOT_TOKEN"] %>
  toruya_user_bot_secret: <%= ENV["TORUYA_USER_BOT_SECRET"] %>
  toruya_user_bot_basic_id: <%= ENV["TORUYA_USER_BOT_BASIC_ID"] %>
  toruya_liff_id: <%= ENV["TORUYA_LIFF_ID"] %>

test:
  secret_key_base: 7784a3a53712f825e4a540bcf804aeeee4d31c9463e82cd7431efb89d61f9c083ac212f5b3ee2f04d5fbac99cc85572f4189edee42fd02806b9ddca1813b4628
  message_encryptor_key: b77f336125acfbaf0e8f486f2114306314d945657b18c33c1585f70c1c241310f14a144bc89bdc8cfa2c351cf2c4b210e2682c89a3d680469e550d81b6db9a1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  message_encryptor_key: <%= ENV["MESSAGE_ENCRYPTOR_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_from_phone: <%= ENV["TWILIO_FROM_PHONE"] %>
  web_push_public_key: <%= ENV["WEB_PUSH_PUBLIC_KEY"] %>
  web_push_private_key: <%= ENV["WEB_PUSH_PRIVATE_KEY"] %>
  toruya_user_bot_token: <%= ENV["TORUYA_USER_BOT_TOKEN"] %>
  toruya_user_bot_secret: <%= ENV["TORUYA_USER_BOT_SECRET"] %>
  toruya_user_bot_basic_id: <%= ENV["TORUYA_USER_BOT_BASIC_ID"] %>
  toruya_liff_id: <%= ENV["TORUYA_LIFF_ID"] %>
